const logo = 'assets/Parent/logo.png';
const schoolNews = 'assets/Parent/School_News.png';
const teacherHome = 'assets/Parent/Teacher.png';
const studentHome = 'assets/Parent/Student.png';
const restaurantHome = 'assets/Parent/Toast.png';
const paymentHome = 'assets/Parent/PayPal.png';
const settingsBottomBar = 'assets/Parent/parent/icons/Settings.svg';
const paymentBottomBar = 'assets/Parent/parent/icons/PayPal.svg';
const homeIconBottomBar = 'assets/Parent/parent/icons/Home.svg';
const masterCardImage = 'assets/Parent/payment_screen/Mastercard.png';
const checkIcon = 'assets/Parent/parent/icons/check.svg';
const mapImage =
    'assets/Parent/bus_screen/🌎 Map Maker_ Alexandria, Alexandria, Egypt (Multi Brand Network).png';
const parentImage = 'assets/Parent/parent/images/ParentImage.png';
const teacherImage = 'assets/Parent/parent/images/teacher_image.png';
const attendenceIcon = 'assets/Parent/parent/icons/attendence_icon.svg';
const calenderIcon = 'assets/Parent/parent/icons/Calendar.svg';
const listIcon = 'assets/Parent/parent/icons/lists_icon.svg';
const mealImage = 'assets/Parent/parent/images/meal.jpg';
